In [1]:
print("helo World")

helo World

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import  RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
True_df=pd.read_csv("archive/True.csv")
Fake_df=pd.read_csv("archive/Fake.csv")

In [3]:
True_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [4]:
Fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
True_df["Label"]=1
Fake_df["Label"]=0

In [6]:
True_df.head()

,title,text,subject,date,Label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [7]:
Fake_df.head()

,title,text,subject,date,Label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [8]:
dataset=pd.concat([Fake_df,True_df],ignore_index=True)

In [9]:
dataset

,title,text,subject,date,Label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [17]:
data=dataset.sample(frac=1).reset_index(drop=True)

In [18]:
data

,title,text,subject,date,Label
0,WOW! Huckabee Asks Nancy Pelosi If She’s “Raci...,Our country deserves a HUD Secretary with the ...,politics,"Dec 5, 2016",0
1,U.S. House Intelligence chairman questions lea...,WASHINGTON (Reuters) - The head of the U.S. Ho...,politicsNews,"February 14, 2017",1
2,"Despite apology, Indonesia asks why U.S. block...",JAKARTA (Reuters) - Indonesia said on Monday i...,worldnews,"October 23, 2017",1
3,HOW A SINGLE FEDERAL BUREAUCRAT OPENED THE DOO...,Meet Alice Miller who single-handedly scr*wed ...,left-news,"May 6, 2015",0
4,Trump has broad power to implement immigration...,NEW YORK/WASHINGTON (Reuters) - President-elec...,politicsNews,"December 5, 2016",1
...,...,...,...,...,...
44893,Trump Just Gave The Most BIZARRE Response For...,Audience members and viewers watching MSNBC s ...,News,"September 8, 2016",0
44894,"Factbox: Trump taps Priebus as chief of staff,...",WASHINGTON (Reuters) - U.S. President-elect Do...,politicsNews,"November 13, 2016",1
44895,Austrian far right says 'very good start' in K...,VIENNA (Reuters) - Austria s far-right Freedom...,worldnews,"October 25, 2017",1
44896,HILARIOUS TRUMP CHRISTMAS VIDEO: “It’s The Mos...,,politics,"Dec 1, 2016",0
44897,Protests Erupt In Charlotte After Cops Kill D...,"Protests have erupted in Charlotte, North Caro...",News,"September 20, 2016",0

In [25]:
X=data[["title","text","subject","date"]]
Y=data["Label"]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [35]:
vectorizer=TfidfVectorizer(stop_words="english",max_df=0.7)
X_train_tfidf = vectorizer.fit_transform(X_train["text"])
X_test_tfidf = vectorizer.transform(X_test["text"])

In [36]:
print(X_train_tfidf.shape) 
print(y_train.shape)

(35918, 111647)
(35918,)

In [37]:
model=RandomForestClassifier()
model.fit(X_train_tfidf, y_train)

RandomForestClassifier()

In [38]:
y_pred = model.predict(X_test_tfidf)

In [39]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9933184855233853

In [ ]:
print( confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[4667   40]
 [  20 4253]]